### ISSUE TITLE
Add a Controller for user profile

### ISSUE THREAD

**Issue by ammaratef45** [ammaratef45/Attendance-API#11]
Add a controller that will be used to:
- get user's data
- edit user's data

**Comment by 0crat** [comment]
The job [#11](https://github.com/ammaratef45/attendance-api/issues/11) assigned to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45), here is [why](https://www.0crat.com/footprint/CH951175M/8ebfaddf-f9d8-4eec-9f83-e599e6c0ec08); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)

**Comment by 0crat** [comment]
It is strongly discouraged to assign jobs to their creators, see [§19](http://www.zerocracy.com/policy.html#19): -15 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)

**Comment by 0pdd** [comment]
@ammaratef45 2 puzzles [#12](https://github.com/ammaratef45/Attendance-API/issues/12), [#13](https://github.com/ammaratef45/Attendance-API/issues/13) are still not solved.

**Comment by 0crat** [comment]
Job was finished in 25 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
Order was finished: +35 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)

**Comment by 0crat** [comment]
The job [#11](https://github.com/ammaratef45/attendance-api/issues/11) is now out of scope

**Comment by 0pdd** [comment]
@ammaratef45 all 2 puzzles are solved here: [#12](https://github.com/ammaratef45/Attendance-API/issues/12), [#13](https://github.com/ammaratef45/Attendance-API/issues/13).
