### ISSUE TITLE
deploy

### ISSUE THREAD

**Issue by ammaratef45** [ammaratef45/Attendance-API#23]
deploy the API to Heroku

**Comment by 0crat** [comment]
The job [#23](https://github.com/ammaratef45/attendance-api/issues/23) assigned to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45), here is [why](https://www.0crat.com/footprint/CH951175M/f11a71b0-f256-4932-aa66-855281a5caae); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
Job was finished in 2 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))
