### ISSUE TITLE
Configure DevOps

### ISSUE THREAD

**Issue by ammaratef45** [ammaratef45/Attendance-API#3]
Add [circleci, rultor, Heroku and pdd] to the project.

**Comment by 0crat** [comment]
Job [#3](https://github.com/ammaratef45/attendance-api/issues/3) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
@ammaratef45[/z](https://www.0crat.com/u/ammaratef45) everybody who has role `DEV` is banned at [#3](https://github.com/ammaratef45/attendance-api/issues/3); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)

**Comment by 0crat** [comment]
The job [#3](https://github.com/ammaratef45/attendance-api/issues/3) assigned to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45), here is [why](https://www.0crat.com/footprint/CH951175M/6ddc1671-fdbb-46c9-a27d-eecccff2c5b6); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)

**Comment by 0crat** [comment]
It is strongly discouraged to assign jobs to their creators, see [§19](http://www.zerocracy.com/policy.html#19): -15 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)

**Comment by 0pdd** [comment]
@ammaratef45 the puzzle [#10](https://github.com/ammaratef45/Attendance-API/issues/10) is still not solved.

**Comment by 0crat** [comment]
The job [#3](https://github.com/ammaratef45/attendance-api/issues/3) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)

**Comment by 0pdd** [comment]
@ammaratef45 the only puzzle [#10](https://github.com/ammaratef45/Attendance-API/issues/10) is solved here.
