### ISSUE TITLE
README

### ISSUE THREAD

**Issue by ammaratef45** [ammaratef45/Attendance-API#4]
make readme looks like other two repos of the project

**Comment by 0crat** [comment]
Job `gh:ammaratef45/attendance-api#4` already assigned to @ammaratef45, can't assign to @ammaratef45

**Comment by 0crat** [comment]
The job [#4](https://github.com/ammaratef45/attendance-api/issues/4) assigned to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45), here is [why](https://www.0crat.com/footprint/CH951175M/10298e82-0111-42ad-8cc1-7d265a151e26); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
It is strongly discouraged to assign jobs to their creators, see [§19](http://www.zerocracy.com/policy.html#19): -15 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)

**Comment by ammaratef45** [comment]
@0crat out

**Comment by 0crat** [comment]
Job was finished in 0 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/ammaratef45/Attendance-API/issues/4#issuecomment-476115779))

@ammaratef45 Job `gh:ammaratef45/attendance-api#4` is not assigned, can't get performer

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/ammaratef45/Attendance-API/issues/4#issuecomment-476115779))

@ammaratef45 The job [#4](https://github.com/ammaratef45/attendance-api/issues/4) is now out of scope

**Comment by 0pdd** [comment]
@ammaratef45 the puzzle [#5](https://github.com/ammaratef45/Attendance-API/issues/5) is still not solved.

**Comment by 0crat** [comment]
Order was finished: +35 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)

**Comment by 0pdd** [comment]
@ammaratef45 the only puzzle [#5](https://github.com/ammaratef45/Attendance-API/issues/5) is solved here.
